---
server:
  port: 9998
spring:
  application:
    name: name-of-gateway
  cloud:
    gateway:
      routes:
        - id: ProjectName
          uri: lb://ProjectName
          predicates:
            - Path=/api/services/v1/**,/web/**
        - id: demo5
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
